### ISSUE TITLE
Broken npm package 0.3.5

### ISSUE THREAD

**Issue by framp** [edorivai/nock-record#19]
Hi @edorivai 

It looks like something went wrong with your last publish, the latest package is empty on npm

**Comment by edorivai** [comment]
Oh no, sorry about that! I don't have time over the weekend, but will fix this on Monday. Quick fix should be to just pin to the latest working version until I fix the package.

**Comment by framp** [comment]
not a problem, I got it working, just raising it up

thanks for the lovely library!

**Comment by edorivai** [comment]
Should be fixed in `0.3.6`
