### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by simlu** [edorivai/nock-record#23]
Your project seems very similar to [node-tdd](https://github.com/blackflux/node-tdd). Maybe take a look and see if we can join forces!

Or you might get inspiration for missing features :)

Cheers, L~

**Comment by edorivai** [comment]
Hi @simlu, sorry for not getting back to you earlier. I don't have too much time to focus on OSS at the moment, but I wouldn't mind going over some concrete suggestions for consolidating efforts if you have any. :)

**Comment by simlu** [comment]
@edorivai After looking again at what this nock-record is capable of, I'd recommend discontinuing in favor of node-tdd. Not trying to force anything, but node-tdd is just much further wrt feature set. There might be some things not possible in node-tdd in the exact way they are possible here, but these should be minor and easy-ish to add. The problem of node-tdd is really that the documentation is not that great. So that needs work for sure. Would love to hear your thoughts!

**Comment by edorivai** [comment]
Am I understanding it correctly that node-tdd tries to be a drop-in replacement for mocha? How does that work exactly, what problem are you trying to solve? How could I use the features if I want to use a different test runner like jest?

**Comment by simlu** [comment]
@edorivai Hello Edo! Sorry for my bad manners. Totally got excited and forgot to write that earlier :)

I think of it more in terms of drop-in extension for mocha (since mocha is still required), but yes that is correct.

Ok, let me try to give some thoughts without rambling too much! There is a trade-of here: nock-record goes the explicit way of forcing the user to manually execute specific asserts. An example would be "assertScopesFinished". node-tdd has the same assertion, but it's just enabled by default and one would have to explicitly disable it. Ultimately it's a design decision, where vanilla nock is on the far "everything is explicit", node-tdd is on the far "everything is magic" side and nock-record is somewhere in the middle.

So with node-tdd we went the path of "we know about recordings and we really know what is best for you - so you only need to enable 'recording' and we'll do the rest for you". That was the reason of tightly integrating with mocha. Virtually one setting and you can convert any test into a test that uses cassettes without having to modify the test or knowing anything about it.

In our experience all tests + recordings always have very similar requirements/problems (e.g. they might break because some request parameter is random etc). So introducing noise to the user to work around or even understand these problems is not necessary. The assert I talked about above is another example. We always want to test that. There shouldn't be a need for the developer to explicitly call that assertion.

And to your last point: Supporting other test frameworks should be easy. It would work similar to how the mocha integration works. We only ever use mocha, so I haven't had the need. But that might be a great extension to node-tdd.

We have thousands of tests that use recordings (some of them have hundreds of records) and node-tdd. So this is definitely a passion project for us that we will support for the foreseeable future.

**Comment by edorivai** [comment]
Hey man, that makes a lot of sense, thanks for taking the time to write this up.

I guess that means there is space for both these libraries, depending on what part of the spectrum you prefer. I personally like jest, so that would currently block me from using node-tdd, and I don't personally have the time to implement support.

Your suggestion about `assertScopesFinished` did inspire me. We could probably do that by default in the `completeRecording()` call, which we could allow you to opt-out of like so:
```js
completeRecording(false); // opt out of asserting nock recording scopes have finished
```

I'll close this issue for now, feel free to open an new one if things change, and thanks again for the input :pray:
