### ISSUE TITLE
Update to nock v13

### ISSUE THREAD

**Issue by vyorkin** [edorivai/nock-record#24]

**Comment by natseg** [comment]
Hello @edorivai!
We use your awesome library in our project and we're super happy with it! 
I have time to spare to update dependencies and create a pull request to support nock v13.

I want to check whether this is okay before starting and if you would have time to review?
Or whether maybe you're already working on this?

Many thanks!

**Comment by edorivai** [comment]
Yes yes, that would be highly appreciated. Since creating this library, I've become a father so OSS dev is deprioritized for the time being. I'd be happy to merge PRs though! :pray:

**Comment by natseg** [comment]
Congrats on fatherhood! And will get started next week and update this issue accordingly. :)

**Comment by simlu** [comment]
@natseg Inviting you to take a look at https://www.npmjs.com/package/node-tdd (disclaimer I'm the author). Not trying to hijack, but we've pretty much started with similar requirements to this project and that then evolved to a lot more. Reference ticket: https://github.com/edorivai/nock-record/issues/23

**Comment by edorivai** [comment]
Merged :tada: - should be available as the current `latest` on npm (v0.3.8).

Thanks @natseg for all the work! :pray:

**Comment by natseg** [comment]
Thanks for merging! I wonder how the package was published, having installed latest `0.3.8`, the package.json does not seem to be in sync with master.
I am sorry, this is annoying...

**Comment by edorivai** [comment]
@natseg sorry about this! I'm not sure what happened either. I've published a new version at `0.3.9`, installed locally and verified that the dependencies have been updated. Please let me know if you can confirm the fix :pray:

**Comment by natseg** [comment]
All good this time around, thanks a lot for checking this :)
